name: Gilang Hardadi
author: Gilang Hardadi
url: http://ghardadi.github.io
baseurl: /
description: Exploring Household Data for Climate Change Policy
github: http://github.com/ghardadi
linkedin: http://www.linkedin.com/in/gilang-hardadi-a26aa232/
email: mailto:gilang.hardadi@indecol.uni-freiburg.de

##Make sure to edit the above fields, especially for disqus.

plugins:
 - jekyll-seo-tag

highlighter: rouge
markdown: kramdown
kramdown:
  extensions: ["tables"]

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
